namespace TileEstimator.Domain.Common;

/// <summary>Base for every persisted entity. Identity is a GUID generated by the domain.</summary>
public abstract class Entity
{
    public Guid Id { get; protected set; } = Guid.NewGuid();
}

/// <summary>Records who created/changed a row and when (always UTC).</summary>
public interface IAuditable
{
    DateTime CreatedAt { get; set; }
    Guid? CreatedBy { get; set; }
    DateTime? UpdatedAt { get; set; }
    Guid? UpdatedBy { get; set; }
}

/// <summary>Business records are soft-deleted; financial and audit records never are.</summary>
public interface ISoftDeletable
{
    bool IsDeleted { get; set; }
    DateTime? DeletedAt { get; set; }
    Guid? DeletedBy { get; set; }
}

/// <summary>Marks a row as belonging to exactly one tenant. Never set from client input.</summary>
public interface ITenantOwned
{
    Guid OrganizationId { get; set; }
}

/// <summary>Optimistic concurrency token for financial records.</summary>
public interface IHasRowVersion
{
    byte[]? RowVersion { get; set; }
}

public abstract class AuditableEntity : Entity, IAuditable
{
    public DateTime CreatedAt { get; set; }
    public Guid? CreatedBy { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public Guid? UpdatedBy { get; set; }
}

public abstract class TenantEntity : AuditableEntity, ITenantOwned, ISoftDeletable
{
    public Guid OrganizationId { get; set; }
    public bool IsDeleted { get; set; }
    public DateTime? DeletedAt { get; set; }
    public Guid? DeletedBy { get; set; }
}
